export const PRODUCT_LIST_REQ = 'PRODUCT_LIST_REQ';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_ERROR';

export const PRODUCT_DETAILS_REQ = 'PRODUCT_REQ';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_ERROR';
